In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Product ID': [1, 2, 3, 4],
    'Product Name': ['t-shirt', 't-shirt', 'skirt', 'skirt'],
    'Color': ['blue', 'green', 'red', 'black']
})

df

   Product ID Product Name  Color
0           1      t-shirt   blue
1           2      t-shirt  green
2           3        skirt    red
3           4        skirt  black

In [3]:
df = pd.DataFrame([
    [1, 'San Diego', 100],
    [2, 'Los Angeles', 120],
    [3, 'San Francisco', 90],
    [4, 'Sacramento', 115]
], columns=['Store ID', 'Location', 'Number of Employees'])

df

   Store ID       Location  Number of Employees
0         1      San Diego                  100
1         2    Los Angeles                  120
2         3  San Francisco                   90
3         4     Sacramento                  115

In [4]:
df = pd.DataFrame([
    ['Chocolate Cake', 'chocolate', 'chocolate', 'Cake shavings'],
    ['Birthday Cake', 'vanilla', 'vanilla', 'rainbow sprinkles'],
    ['Carrot Cake', 'carrot', 'cream cheese', 'almonds']
], columns=['name', 'cake_flavor', 'frosting_flavor', 'topping'])

df.to_csv('cupcakes.csv', index=False)

In [5]:
df = pd.read_csv('sample.csv')
df

            City  Population  Median Age
0      Maplewood      100000          40
1          Wayne      350000          33
2  Forrest Hills      300000          35
3        Paramus      400000          55
4     Hackensack      290000          39

In [6]:
df = pd.read_csv('imdb.csv', delimiter='\t')
df.head()

,Unnamed: 0,id,name,genre,year,imdb_rating
0,0,1,Avatar,action,2009,7.9
1,1,2,Jurassic World,action,2015,7.3
2,2,3,The Avengers,action,2012,8.1
3,3,4,The Dark Knight,action,2008,9.0
4,4,5,Star Wars: Episode I - The Phantom Menace,action,1999,6.6

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   220 non-null    int64
 1   id           220 non-null    int64
 2   name         220 non-null    str
 3   genre        220 non-null    str
 4   year         220 non-null    int64
 5   imdb_rating  220 non-null    float64
dtypes: float64(1), int64(3), str(2)
memory usage: 10.4 KB

In [8]:
df = pd.DataFrame([
    ['January', 100, 100, 23, 100],
    ['February', 51, 45, 145, 45],
    ['March', 81, 96, 65, 96],
    ['April', 80, 80, 54, 180],
    ['May', 51, 54, 54, 154],
    ['June', 112, 109, 79, 129]
], columns=['month', 'clinic_east', 'clinic_north', 'clinic_south', 'clinic_west'])

clinic_north = df['clinic_north']
type(clinic_north)

pandas.Series

In [9]:
type(df)

pandas.DataFrame

In [10]:
clinic_north_south = df[['clinic_north', 'clinic_south']]
type(clinic_north_south)

pandas.DataFrame

In [11]:
march = df.iloc[2]
march

month           March
clinic_east        81
clinic_north       96
clinic_south       65
clinic_west        96
Name: 2, dtype: object

In [12]:
april_may_june = df.iloc[3:6]
april_may_june

   month  clinic_east  clinic_north  clinic_south  clinic_west
3  April           80            80            54          180
4    May           51            54            54          154
5   June          112           109            79          129