In [1]:
import pandas as pd
import numpy as np
orders = pd.read_csv('orders.csv', delimiter="\t")

In [2]:
most_expensive = orders.price.max()
num_colors = orders.shoe_color.nunique()

orders.head(10)

,id,first_name,last_name,email,shoe_type,shoe_material,shoe_color,price
0,41874,Kyle,Peck,KylePeck71@gmail.com,ballet flats,faux-leather,black,385.0
1,31349,Elizabeth,Velazquez,EVelazquez1971@gmail.com,boots,fabric,brown,388.0
2,43416,Keith,Saunders,KS4047@gmail.com,sandles,leather,navy,346.0
3,56054,Ryan,Sweeney,RyanSweeney14@outlook.com,sandles,fabric,brown,344.0
4,77402,Donna,Blankenship,DB3807@gmail.com,stilettos,fabric,brown,289.0
5,97148,Albert,Dillon,Albert.Dillon@gmail.com,wedges,fabric,brown,266.0
6,19998,Judith,Hewitt,JudithHewitt98@gmail.com,stilettos,leather,black,395.0
7,83290,Kayla,Hardin,Kayla.Hardin@gmail.com,stilettos,leather,white,241.0
8,77867,Steven,Blankenship,Steven.Blankenship@gmail.com,wedges,leather,navy,266.0
9,54885,Carol,Mclaughlin,CM3415@gmail.com,ballet flats,faux-leather,brown,440.0

In [3]:
pricey_shoes = orders.groupby('shoe_type').price.max()
pricey_shoes

shoe_type
ballet flats    481.0
boots           478.0
clogs           493.0
sandles         456.0
stilettos       487.0
wedges          461.0
Name: price, dtype: float64

In [4]:
type(pricey_shoes)

pandas.Series

In [5]:
pricey_shoes = orders.groupby('shoe_type').price.max().reset_index()
pricey_shoes

      shoe_type  price
0  ballet flats  481.0
1         boots  478.0
2         clogs  493.0
3       sandles  456.0
4     stilettos  487.0
5        wedges  461.0

In [6]:
type(pricey_shoes)

pandas.DataFrame

In [7]:
cheap_shoes = orders.groupby('shoe_color').price.apply(lambda x: np.nanpercentile(x, 25)).reset_index()
cheap_shoes

  shoe_color  price
0      black    NaN
1      brown  193.5
2       navy  205.5
3        red  250.0
4      white  196.0

In [8]:
shoe_counts = orders.groupby(['shoe_type', 'shoe_color']).id.count().reset_index()
shoe_counts

       shoe_type shoe_color  id
0   ballet flats      black   2
1   ballet flats      brown   5
2   ballet flats        red   3
3   ballet flats      white   5
4          boots      black   3
5          boots      brown   5
6          boots       navy   6
7          boots        red   2
8          boots      white   3
9          clogs      black   4
10         clogs      brown   6
11         clogs       navy   1
12         clogs        red   4
13         clogs      white   1
14       sandles      black   1
15       sandles      brown   4
16       sandles       navy   5
17       sandles        red   3
18       sandles      white   4
19     stilettos      black   5
20     stilettos      brown   3
21     stilettos       navy   2
22     stilettos        red   2
23     stilettos      white   2
24        wedges      black   3
25        wedges      brown   4
26        wedges       navy   4
27        wedges        red   5
28        wedges      white   2